version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bikeshare_data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./dataset:/var/lib/postgresql/data/dataset
      - ./sql:/var/lib/postgresql/data/sql
    ports:
      - 5432:5432
    command: ["/bin/bash", "/var/lib/postgresql/data/sql/init.sh"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5